// Auto-generated by bsp_gen. DO NOT EDIT.
use crate::board_defs::BoardPeripherals;
use esp_hal::{gpio::Pin, peripherals::Peripherals};
impl BoardPeripherals {
    pub fn from_peripherals(p: Peripherals) -> Self {
        BoardPeripherals {
            led: p.GPIO10.degrade(),
        }
    }
}
