use anyhow::{Context, Result};
use clap::Parser;

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// JSON input file from netlistquery
    input: PathBuf,

    /// Rust output file
    output: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let content = fs::read_to_string(&args.input)
        .with_context(|| format!("Failed to read input JSON file {}", args.input.display()))?;

    let data: HashMap<String, Vec<Vec<String>>> = serde_json::from_str(&content)
        .context("Invalid JSON format. Expected mapping of pin names to array of rows.")?;

    let mut out = String::new();
    out.push_str("// Auto-generated by bsp_gen. DO NOT EDIT.\n");

    out.push_str("use esp_hal::{gpio::Pin, peripherals::Peripherals};\n");
    out.push_str("use crate::board_defs::BoardPeripherals;\n");

    out.push_str("impl BoardPeripherals {\n");
    out.push_str("    pub fn from_peripherals(p: Peripherals) -> Self {\n");
    out.push_str("        BoardPeripherals {\n");

    // We expect the JSON to be like: {"led": [["GPIO10/TOUCH10/ADC1_CH9/FSPICS0/FSPIIO4/SUBSPICS0"]]}
    for (pin_name, rows) in &data {
        if let Some(first_row) = rows.first() {
            if let Some(raw_func) = first_row.first() {
                // Extract the first part before '/'
                let pin_base = raw_func.split('/').next().unwrap_or(raw_func);
                out.push_str(&format!(
                    "            {}: p.{}.degrade(),\n",
                    pin_name, pin_base
                ));
            }
        }
    }

    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(&args.output, out).context("Failed to write output file")?;
    println!("Generated BSP file: {}", args.output.display());

    Ok(())
}
